spring:
  application:
    name: miscroservice-provider-user
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://yanlg:1@localhost:8761/eureka  
  instance:
    prefer-ip-address: true    